micronaut:
   environment: prod
   server:
      port: 10900
      host: localhost
datasources:
   default:
      url: "jdbc:postgresql://localhost:5432/cynergidb"
      maximumPoolSize: 10
      username: cynergiuser
      password: cynergiuser2019
