micronaut:
   environment: prod
datasources:
   default:
      url: "jdbc:postgresql://localhost:5432/cynergidb"
      maximumPoolSize: 10
      username: cynergiuser
      password: 2h@rd2rememberNow
