micronaut:
   environment: local
   router:
      static-resources:
         swagger:
            paths: classpath:META-INF/swagger
            mapping: /swagger/**
datasources:
   default:
      url: "jdbc:postgresql://localhost:6432/cynergidb"
      username: postgres
      password: password
      maximumPoolSize: 1
