micronaut:
   environment: local
datasources:
   default:
      url: "jdbc:postgresql://localhost:5434/cynergidb"
      username: postgres
      password: password
flyway:
   datasources:
      default:
         locations: classpath:db/migration/postgres

