micronaut:
   application:
      name: cynergi-middleware
datasources:
   default:
      driverClassName: org.postgresql.Driver
      connectionInitSql: SELECT 1
flyway:
   datasources:
      default:
         locations: classpath:db/migration/postgres
         clean-disabled: true
