micronaut:
   application:
      name: cynergi-middleware
jackson:
   serialization:
      writeDatesAsTimestamps: false
   deserialization:
      failOnUnknownProperties: false
datasources:
   default:
      driverClassName: org.postgresql.Driver
      connectionInitSql: SELECT 1
flyway:
   datasources:
      default:
         locations: classpath:db/migration/postgres
         clean-disabled: true
