micronaut:
   application:
      name: cynergi-middleware
postgres:
   reactive:
      client:
         port: 5432
         database: cynergidb
         maxSize: 5
datasources:
   default:
      driverClassName: org.postgresql.Driver
      connectionInitSql: SELECT 1
      maximumPoolSize: 2
flyway:
   url: "jdbc:postgresql://${postgres.reactive.client.host}:${postgres.reactive.client.port}/${postgres.reactive.client.database}"
   user: "${postgres.reactive.client.user}"
   password: "${postgres.reactive.client.password}"
