micronaut:
   application:
      name: cynergi-middleware
   caches:
      user-cache:
         maximum-size: 50
         expire-after-write: 3600s
      company-cache:
         maximum-size: 10
         expire-after-write: 3600s
      department-cache:
         maximum-size: 100
         expire-after-write: 3600s
      store-cache:
         maximum-size: 200
         expire-after-write: 3600s
   security:
      enabled: true
      endpoints:
         login:
            enabled: true
         logout:
            enabled: true
      token:
         jwt:
            enabled: true
            generator:
               access-token-expiration: 43200 # 12 hours
               refresh-token-expiration: 86400 # 24 hours
            bearer:
               enabled: true
            signatures:
               secret:
                  generator:
                     jws-algorithm: HS256
jackson:
   serialization:
      writeDatesAsTimestamps: false
   deserialization:
      failOnUnknownProperties: false
datasources:
   default:
      driverClassName: org.postgresql.Driver
      connectionInitSql: SELECT 1
endpoints:
   health:
      enabled: false
      postgres:
         reactive:
            enabled: false
flyway:
   datasources:
      default:
         locations: classpath:db/migration/postgres
         clean-disabled: true
         async: false
