micronaut:
   environment: cstdevelop
   server:
      port: 10900
      host: localhost
      security.token.jwt.signatures.secret.generator.secret: 9kfdjiefj838fjao8fjo9fj384784ikfjaoijdfo8jfejfkdodkflijoij
postgres: # postgres reactive client is configured for use by reactive parts of the system such as authentication
   reactive:
      client:
         port: 5432
         host: localhost
         database: cynergidb
         user: cynergiuser
         password: cynergiuser2019
         maxSize: 10
datasources:
   default:
      url: "jdbc:postgresql://${postgres.reactive.client.host}:${postgres.reactive.client.port}/${postgres.reactive.client.database}"
      username: "${postgres.reactive.client.user}"
      password: "${postgres.reactive.client.password}"
      maximumPoolSize: 1
flyway:
   datasources:
      default:
         clean-on-validation-error: true
         clean-disabled: false
cynergi:
   security:
      jwt:
         pem:
            path: "classpath:security/local-dev.pem" #openssl genrsa -out security/local-dev.pem 2048
   worker:
      pool:
         size: 5
   reportal:
      file:
         location: "/tmp/WebPortal/ZWebRoot/cynrep/reports"
