micronaut:
   environment: demo
datasources:
   default:
      url: "jdbc:postgresql://localhost:5432/cynergidbdemo"
      username: postgres
      password: password
flyway:
   datasources:
      default:
         clean-disabled: false
