---
micronaut:
   environment: test
---
postgres:
   reactive:
      client:
         port: 6432
         database: cynergidbtest
         host: localhost
         user: postgres
         password: password
---
datasources:
   primary:
      url: "jdbc:postgresql://${postgres.reactive.client.host}:${postgres.reactive.client.port}/${postgres.reactive.client.database}"
      user: "${postgres.reactive.client.user}"
      password: "${postgres.reactive.client.password}"
---
flyway:
   datasources:
      primary:
         locations: classpath:db/migration/postgres

