version: '3.8'
networks:
   cynerginet:
      name: cynerginet
services:
   cynergibasedb:
      image: cynergibasedb
      build:
         network: host
         context: cynergibasedb
         dockerfile: cynergibasedb.dockerfile
   cynergidb:
      container_name: cynergidb
      networks:
         - cynerginet
      build:
         context: cynergidb
         dockerfile: cynergidb.dockerfile
      logging:
         driver: "json-file"
         options:
            max-file: "5"
            max-size: "10m"
      ports:
         - "6432:5432"
      volumes:
         - ./db/DatabaseDumps:/tmp/dumps
      environment:
         - POSTGRES_PASSWORD=password
      restart: 'no'
   cynergidbready:
      container_name: cynergidbready
      image: cynergibasedb
      networks:
         - cynerginet
      depends_on:
         - cynergidb
      stdin_open: true
      tty: true
      command: [ "/tmp/db-ready.sh", "cynergidb" ]
   cynergidbpsql:
      container_name: cynergidbpsql
      image: cynergibasedb
      depends_on:
         - cynergidb
      networks:
         - cynerginet
      logging:
         driver: "json-file"
         options:
            max-file: "5"
            max-size: "10m"
      stdin_open: true
      tty: true
      command: [ "/usr/local/bin/psql", "--host=cynergidb", "--port=5432", "cynergidb", "cynergiuser" ]
   fastinfopsql:
      container_name: fastinfopsql
      image: cynergibasedb
      depends_on:
         - cynergidb
      networks:
         - cynerginet
      logging:
         driver: "json-file"
         options:
            max-file: "5"
            max-size: "10m"
      command: [ "/usr/local/bin/psql", "--host=cynergidb", "--port=5432", "fastinfo_production", "postgres" ]
   cynergitestdb:
      container_name: cynergitestdb
      networks:
         - cynerginet
      build:
         context: cynergitestdb
         dockerfile: cynergitestdb.dockerfile
      logging:
         driver: "json-file"
         options:
            max-file: "5"
            max-size: "10m"
      ports:
         - "7432:5432"
      tmpfs: /var/lib/postgresql/data:rw
      environment:
         - POSTGRES_DB=cynergitestdb
         - POSTGRES_PASSWORD=password
      restart: 'no'
      volumes:
         - ./cynergitestdb/fastinfo:/tmp/fastinfo
   cynergitestdbready:
      container_name: cynergitestdbready
      image: cynergibasedb
      logging:
         driver: "json-file"
         options:
            max-file: "5"
            max-size: "10m"
      depends_on:
         - cynergitestdb
      networks:
         - cynerginet
      stdin_open: true
      tty: true
      command: [ "/tmp/db-ready.sh", "cynergitestdb" ]
   cynergitestdbpsql:
      container_name: cynergitestdbpsql
      image: cynergibasedb
      logging:
         driver: "json-file"
         options:
            max-file: "5"
            max-size: "10m"
      depends_on:
         - cynergitestdb
      networks:
         - cynerginet
      stdin_open: true
      tty: true
      command: [ "/usr/local/bin/psql", "--host=cynergitestdb", "--port=5432", "cynergitestdb", "postgres" ]
   cynmid:
      container_name: cynmid
      image: bellsoft/liberica-openjdk-alpine:11.0.12
      logging:
         driver: "json-file"
         options:
            max-file: "5"
            max-size: "10m"
      depends_on:
         - cynergidb
      networks:
         - cynerginet
      links:
         - cynergidb
      stdin_open: true
      tty: true
      volumes:
         - ../../build/libs:/tmp/cynergi-middleware
      ports:
         - "8080:8080"
      environment:
         - DATASOURCES_DEFAULT_URL=jdbc:postgresql://cynergidb:5432/cynergidb
      command: [ "java", "-Dmicronaut.environments=development", "-jar", "/tmp/cynergi-middleware/cynergi-middleware.jar" ]
   cynmidintegration:
      container_name: cynmidintegration
      image: bellsoft/liberica-openjdk-alpine:11.0.12
      logging:
         driver: "json-file"
         options:
            max-file: "5"
            max-size: "10m"
      depends_on:
         - cynergitestdb
      networks:
         - cynerginet
      links:
         - cynergitestdb
      volumes:
         - ../../build/libs:/tmp/cynergi-middleware
      ports:
         - "8080:8080"
      stdin_open: true
      tty: true
      environment:
         - DATASOURCES_DEFAULT_URL=jdbc:postgresql://cynergitestdb:5432/cynergitestdb
      command: [ "java", "-Dmicronaut.environments=integration", "-jar", "/tmp/cynergi-middleware/cynergi-middleware.jar" ]
