version: '3.5'
networks:
   cynerginet:
      name: cynerginet
services:
   cynergipgdb:
      container_name: cynergipgdb
      image: cynergipgdbbase
      build:
         context: cynergipgdb
         dockerfile: cynergipgdb.dockerfile
   cynergidb:
      container_name: cynergidb
      networks:
         - cynerginet
      build:
         context: cynergidb
         dockerfile: cynergidb.dockerfile
      ports:
         - "6432:5432"
      volumes:
         - ./db/DatabaseDumps:/tmp/dumps
      environment:
         - POSTGRES_PASSWORD=password
      restart: 'no'
   cynergidbready:
      container_name: cynergidbready
      image: cynergipgdbbase
      networks:
         - cynerginet
      depends_on:
         - cynergidb
      stdin_open: true
      tty: true
      command: [ "/root/db-ready.sh", "cynergidb" ]
   cynergidbpsql:
      container_name: cynergidbpsql
      image: cynergipgdbbase
      depends_on:
         - cynergidb
      networks:
         - cynerginet
      stdin_open: true
      tty: true
      command: [ "/usr/local/bin/psql", "--host=cynergidb", "--port=5432", "cynergidb", "cynergiuser" ]
   cynergidevelopdbpsql:
      container_name: cynergidbpsql
      image: cynergipgdbbase
      depends_on:
         - cynergidb
      networks:
         - cynerginet
      stdin_open: true
      tty: true
      command: [ "/usr/local/bin/psql", "--host=cynergidb", "--port=5432", "cynergidevelopdb", "cynergiuser" ]
   fastinfopsql:
      container_name: fastinfopsql
      depends_on:
         - cynergidb
      networks:
         - cynerginet
      build:
         context: db
         dockerfile: fastinfosnapshot.dockerfile
      command: [ "/usr/local/bin/psql", "--host=cynergidb", "--port=5432", "fastinfo_production", "postgres" ]
   cynergitestdb:
      container_name: cynergitestdb
      networks:
         - cynerginet
      build:
         context: cynergitestdb
         dockerfile: cynergitestdb.dockerfile
      ports:
         - "7432:5432"
      tmpfs: /var/lib/postgresql/data:rw
      environment:
         - POSTGRES_DB=cynergitestdb
         - POSTGRES_PASSWORD=password
      restart: 'no'
      volumes:
         - ./cynergitestdb/fastinfo:/tmp/fastinfo
   cynergitestdbready:
      container_name: cynergitestdbready
      image: cynergipgdbbase
      depends_on:
         - cynergitestdb
      networks:
         - cynerginet
      stdin_open: true
      tty: true
      command: [ "/root/db-ready.sh", "cynergitestdb" ]
   cynergitestdbpsql:
      container_name: cynergitestdbpsql
      image: cynergipgdbbase
      depends_on:
         - cynergitestdb
      networks:
         - cynerginet
      stdin_open: true
      tty: true
      command: [ "/usr/local/bin/psql", "--host=cynergitestdb", "--port=5432", "cynergitestdb", "postgres" ]
   cynmidintegration:
      container_name: cynmidintegration
      depends_on:
         - cynergitestdb
      networks:
         - cynerginet
      links:
         - cynergitestdb
      build:
         context: cynmidintegration
         dockerfile: cynmid.dockerfile
      volumes:
         - ../../build/libs:/tmp/cynergi-middleware
      stdin_open: true
      tty: true
      command: ["java", "-Dmicronaut.environments=integration", "-Dpostgres.reactive.client.host=cynergitestdb", "-jar", "/tmp/cynergi-middleware/cynergi-middleware-r4-all.jar"]
