version: '3.8'
networks:
   cynerginet:
      name: cynerginet
volumes:
   gradleCache:

services:
   cynergibasedb:
      image: cynergibasedb
      build:
         network: host
         context: cynergibasedb
         dockerfile: cynergibasedb.dockerfile
   cynergidb:
      container_name: cynergidb
      networks:
         - cynerginet
      build:
         context: cynergidb
         dockerfile: cynergidb.dockerfile
      logging:
         driver: "json-file"
         options:
            max-file: "5"
            max-size: "10m"
      ports:
         - "6432:5432"
      volumes:
         - ./db/DatabaseDumps:/tmp/dumps
         - ../../src/main/resources/db/migration/postgres/:/tmp/migrations
      environment:
         - POSTGRES_USER=postgres
         - POSTGRES_PASSWORD=password
         - POSTGRES_DB=postgres
      restart: 'no'
      healthcheck:
         test: [ "CMD-SHELL", "pg_isready --host=cynergidb -U cynergiuser -d cynergidb --port=5432" ]
         interval: 10s
         timeout: 5s
         retries: 15
   cynergidbpsql:
      container_name: cynergidbpsql
      image: cynergibasedb
      depends_on:
         - cynergidb
      networks:
         - cynerginet
      logging:
         driver: "json-file"
         options:
            max-file: "5"
            max-size: "10m"
      stdin_open: true
      tty: true
      command: [ "psql", "--host=cynergidb", "--port=5432", "cynergidb", "cynergiuser" ]
   fastinfopsql:
      container_name: fastinfopsql
      image: cynergibasedb
      depends_on:
         - cynergidb
      networks:
         - cynerginet
      logging:
         driver: "json-file"
         options:
            max-file: "5"
            max-size: "10m"
      command: [ "psql", "--host=cynergidb", "--port=5432", "fastinfo_production", "fastinfo_dba" ]
   sftpdev:
      container_name: sftpdev
      networks:
         - cynerginet
      build:
         network: host
         context: sftp
         dockerfile: sftp.dockerfile
         args:
            GROUP_ID: ${GROUP_ID:-1001}
            USER_ID: ${USER_ID:-1001}
      ports:
         - "2222:22"
      logging:
         driver: "json-file"
         options:
            max-file: "5"
            max-size: "10m"
   cynmid:
      container_name: cynmid
      build:
         context: ../../
         dockerfile: support/development/cynmid/cynmid.dockerfile
         args:
            GROUP_ID: ${GROUP_ID:-1001}
            USER_ID: ${USER_ID:-1001}
      logging:
         driver: "json-file"
         options:
            max-file: "5"
            max-size: "10m"
      depends_on:
         - cynergidb
         - sftpdev
      networks:
         - cynerginet
      ports:
         - "8080:8080"
      environment:
         - DATASOURCES_DEFAULT_URL=jdbc:postgresql://cynergidb:5432/cynergidb
      volumes:
         - gradleCache:/home/jenkins/.gradle
      command: [ "./gradlew", "--no-daemon", "--info", "clean", "shadowJar", "&&", "java", "-Dmicronaut.environments=development", "-jar", "/opt/cynergi-middleware/build/libs/cynergi-middleware.jar" ]

   cynergitestdb:
      container_name: cynergitestdb
      networks:
         - cynerginet
      build:
         context: cynergitestdb
         dockerfile: cynergitestdb.dockerfile
      logging:
         driver: "json-file"
         options:
            max-file: "5"
            max-size: "10m"
      ports:
         - "7432:5432"
      tmpfs: /var/lib/postgresql/data:rw
      environment:
         - POSTGRES_DB=cynergitestdb
         - POSTGRES_PASSWORD=password
      restart: 'no'
      volumes:
         - ./cynergitestdb/fastinfo:/tmp/fastinfo
   cynergitestdbready:
      container_name: cynergitestdbready
      image: cynergibasedb
      logging:
         driver: "json-file"
         options:
            max-file: "5"
            max-size: "10m"
      depends_on:
         - cynergitestdb
      networks:
         - cynerginet
      stdin_open: true
      tty: true
      command: [ "/opt/scripts/db-ready.sh", "cynergitestdb" ]
   cynergitestdbpsql:
      container_name: cynergitestdbpsql
      image: cynergibasedb
      logging:
         driver: "json-file"
         options:
            max-file: "5"
            max-size: "10m"
      depends_on:
         - cynergitestdb
      networks:
         - cynerginet
      stdin_open: true
      tty: true
      command: [ "psql", "--host=cynergitestdb", "--port=5432", "cynergitestdb", "postgres" ]
   sftptest:
      container_name: sftptest
      networks:
         - cynerginet
      build:
         context: sftp
         dockerfile: sftp.dockerfile
         args:
            GROUP_ID: ${GROUP_ID:-1001}
            USER_ID: ${USER_ID:-1001}
      ports:
         - "2223:22"
      logging:
         driver: "json-file"
         options:
            max-file: "5"
            max-size: "10m"

   cynmidintegration:
      container_name: cynmidintegration
      image: bellsoft/liberica-openjdk-alpine:11.0.12
      logging:
         driver: "json-file"
         options:
            max-file: "5"
            max-size: "10m"
      depends_on:
         - cynergitestdb
      networks:
         - cynerginet
      links:
         - cynergitestdb
      volumes:
         - ../../build/libs:/tmp/cynergi-middleware
      ports:
         - "8080:8080"
      stdin_open: true
      tty: true
      environment:
         - DATASOURCES_DEFAULT_URL=jdbc:postgresql://cynergitestdb:5432/cynergitestdb
      command: [ "java", "-Dmicronaut.environments=integration", "-jar", "/tmp/cynergi-middleware/cynergi-middleware.jar" ]
