#!/usr/bin/env zsh

cd "${0%/*}" # see: https://stackoverflow.com/questions/6393551/what-is-the-meaning-of-0-in-a-bash-script for explanation
# need to make sure the current directory is that of this script in the cynergi-middleware/support/.cyn/ so that the child scripts will work correctly
# plan is to use direnv https://direnv.net/ to setup the path variable using the PATH_add function in a .envrc file

case "$@" in
  "db start development")
    ./db/start/development.sh
    ;;
  "db psql development cynergidb")
    ./db/psql/development/cynergidb.sh
    ;;
  "db psql development cynergidb")
    ./db/psql/development/cynergidevelopdb.sh
    ;;
  *)
    echo "Unknown $@"
    exit 1
  ;;
esac
