#!/usr/bin/env bash
show() {
  TYPE="$1"; shift
  for i in $(echo $*)
  do
     echo "$TYPE: $i"
  done
}
drive() {
  unset DIRS
  unset FILES
  for i in $(echo "$*")
  do
     [ -f $i ] && FILES="$FILES $(basename $i)"
     [ -d $i ] && DIRS="$DIRS $(basename $i)"
  done
  [ "$FILES" ] && show "Script" "$FILES"
  [ "$DIRS" ] && show "Dir" "$DIRS"
  exit 1
}

cd "${0%/*}" # see: https://stackoverflow.com/questions/6393551/what-is-the-meaning-of-0-in-a-bash-script for explanation
# need to make sure the current directory is that of this script in the cynergi-middleware/support/.cyn/ so that the child scripts will work correctly
# plan is to use direnv https://direnv.net/ to setup the path variable using the PATH_add function in a .envrc file

unset POSSBILE
unset SCRIPT
CMD="./commands"
while [ "$1" ]
do
  POSSIBLE=$(find $CMD/${1}* -maxdepth 0 2>/dev/null)
  [ $? -ne 0 ] && echo "No possible matches for $1" && POSSIBLE="$CMD"
  if [ $(echo "$POSSIBLE" | wc -l) -eq 1 ]; then
     CMD="$POSSIBLE"
     [ -f "$POSSIBLE" ] && SCRIPT=true
  else
     drive "$POSSIBLE"
  fi
  shift
done
##########################################
if [ "$SCRIPT" ]; then
  echo "running --> $POSSIBLE"
  eval $POSSIBLE
else
  [ ! "$POSSIBLE" ] && POSSIBLE="$CMD"
  LAST=$(find $POSSIBLE -maxdepth 1 | tail -n +2)
  drive "$LAST"
fi
