package com.cynergisuite.middleware.purchase.order.detail.infrastructure

import com.cynergisuite.domain.PageRequest
import com.cynergisuite.domain.SimpleLegacyIdentifiableEntity
import com.cynergisuite.domain.infrastructure.RepositoryPage
import com.cynergisuite.extensions.findFirstOrNull
import com.cynergisuite.extensions.getIntOrNull
import com.cynergisuite.extensions.getLocalDateOrNull
import com.cynergisuite.extensions.getUuid
import com.cynergisuite.extensions.insertReturning
import com.cynergisuite.extensions.queryPaged
import com.cynergisuite.extensions.softDelete
import com.cynergisuite.extensions.updateReturning
import com.cynergisuite.middleware.company.CompanyEntity
import com.cynergisuite.middleware.error.NotFoundException
import com.cynergisuite.middleware.purchase.order.detail.PurchaseOrderDetailEntity
import com.cynergisuite.middleware.purchase.order.infrastructure.PurchaseOrderRepository
import com.cynergisuite.middleware.purchase.order.type.infrastructure.ExceptionIndicatorTypeRepository
import com.cynergisuite.middleware.purchase.order.type.infrastructure.PurchaseOrderRequisitionIndicatorTypeRepository
import com.cynergisuite.middleware.purchase.order.type.infrastructure.PurchaseOrderStatusTypeRepository
import com.cynergisuite.middleware.vendor.infrastructure.VendorRepository
import io.micronaut.transaction.annotation.ReadOnly
import org.apache.commons.lang3.StringUtils.EMPTY
import org.jdbi.v3.core.Jdbi
import org.slf4j.Logger
import org.slf4j.LoggerFactory
import java.sql.ResultSet
import java.util.UUID
import javax.inject.Inject
import javax.inject.Singleton
import javax.transaction.Transactional

@Singleton
class PurchaseOrderDetailRepository @Inject constructor(
   private val jdbc: Jdbi,
   private val purchaseOrderRepository: PurchaseOrderRepository,
   private val vendorRepository: VendorRepository,
   private val statusTypeRepository: PurchaseOrderStatusTypeRepository,
   private val purchaseOrderRequisitionIndicatorTypeRepository: PurchaseOrderRequisitionIndicatorTypeRepository,
   private val exceptionIndicatorTypeRepository: ExceptionIndicatorTypeRepository
) {
   private val logger: Logger = LoggerFactory.getLogger(PurchaseOrderDetailRepository::class.java)

   fun selectBaseQuery(): String {
      return """
         WITH purchase_order_header AS (
            ${purchaseOrderRepository.selectBaseQuery()}
         ),
         vendor AS (
            ${vendorRepository.baseSelectQuery()}
         )
         SELECT
            poDetail.id                                               AS poDetail_id,
            poDetail.time_created                                     AS poDetail_time_created,
            poDetail.time_updated                                     AS poDetail_time_updated,
            poDetail.number                                           AS poDetail_number,
            poDetail.company_id                                       AS poDetail_company_id,
            poDetail.itemfile_number_sfk                              AS poDetail_itemfile_number_sfk,
            poDetail.order_quantity                                   AS poDetail_order_quantity,
            poDetail.received_quantity                                AS poDetail_received_quantity,
            poDetail.cost                                             AS poDetail_cost,
            poDetail.message                                          AS poDetail_message,
            poDetail.color_id_sfk                                     AS poDetail_color_id_sfk,
            poDetail.fabric_id_sfk                                    AS poDetail_fabric_id_sfk,
            poDetail.cancelled_quantity                               AS poDetail_cancelled_quantity,
            poDetail.cancelled_temp_quantity                          AS poDetail_cancelled_temp_quantity,
            poDetail.ship_to_id_sfk                                   AS poDetail_ship_to_id_sfk,
            poDetail.required_date                                    AS poDetail_required_date,
            poDetail.date_ordered                                     AS poDetail_date_ordered,
            poDetail.freight_per_item                                 AS poDetail_freight_per_item,
            poDetail.temp_quantity_to_receive                         AS poDetail_temp_quantity_to_receive,
            poDetail.last_received_date                               AS poDetail_last_received_date,
            poDetail.landed_cost                                      AS poDetail_landed_cost,
            poDetail.converted_purchase_order_number                  AS poDetail_converted_purchase_order_number,
            poDetail.approved_ind                                     AS poDetail_approved_ind,
            poDetail.deleted                                          AS poDetail_deleted,
            po.po_id                                                  AS poDetail_po_id,
            po.po_time_created                                        AS poDetail_po_time_created,
            po.po_time_updated                                        AS poDetail_po_time_updated,
            po.po_number                                              AS poDetail_po_number,
            po.po_comp_id                                             AS poDetail_po_comp_id,
            po.po_order_date                                          AS poDetail_po_order_date,
            po.po_total_amount                                        AS poDetail_po_total_amount,
            po.po_received_amount                                     AS poDetail_po_received_amount,
            po.po_paid_amount                                         AS poDetail_po_paid_amount,
            po.po_required_date                                       AS poDetail_po_required_date,
            po.po_message                                             AS poDetail_po_message,
            po.po_total_landed_amount                                 AS poDetail_po_total_landed_amount,
            po.po_total_freight_amount                                AS poDetail_po_total_freight_amount,
            po.po_vendor_submitted_time                               AS poDetail_po_vendor_submitted_time,
            po.po_ecommerce_indicator                                 AS poDetail_po_ecommerce_indicator,
            po.po_deleted                                             AS poDetail_po_deleted,
            po.po_vendor_id                                           AS poDetail_po_vendor_id,
            po.po_vendor_time_created                                 AS poDetail_po_vendor_time_created,
            po.po_vendor_time_updated                                 AS poDetail_po_vendor_time_updated,
            po.po_vendor_company_id                                   AS poDetail_po_vendor_company_id,
            po.po_vendor_number                                       AS poDetail_po_vendor_number,
            po.po_vendor_name                                         AS poDetail_po_vendor_name,
            po.po_vendor_account_number                               AS poDetail_po_vendor_account_number,
            po.po_vendor_pay_to_id                                    AS poDetail_po_vendor_pay_to_id,
            po.po_vendor_freight_on_board_type_id                     AS poDetail_po_vendor_freight_on_board_type_id,
            po.po_vendor_vendor_payment_term_id                       AS poDetail_po_vendor_vendor_payment_term_id,
            po.po_vendor_normal_days                                  AS poDetail_po_vendor_normal_days,
            po.po_vendor_return_policy                                AS poDetail_po_vendor_return_policy,
            po.po_vendor_ship_via_id                                  AS poDetail_po_vendor_ship_via_id,
            po.po_vendor_group_id                                     AS poDetail_po_vendor_group_id,
            po.po_vendor_minimum_quantity                             AS poDetail_po_vendor_minimum_quantity,
            po.po_vendor_minimum_amount                               AS poDetail_po_vendor_minimum_amount,
            po.po_vendor_free_ship_quantity                           AS poDetail_po_vendor_free_ship_quantity,
            po.po_vendor_free_ship_amount                             AS poDetail_po_vendor_free_ship_amount,
            po.po_vendor_vendor_1099                                  AS poDetail_po_vendor_vendor_1099,
            po.po_vendor_federal_id_number                            AS poDetail_po_vendor_federal_id_number,
            po.po_vendor_sales_representative_name                    AS poDetail_po_vendor_sales_representative_name,
            po.po_vendor_sales_representative_fax                     AS poDetail_po_vendor_sales_representative_fax,
            po.po_vendor_separate_check                               AS poDetail_po_vendor_separate_check,
            po.po_vendor_bump_percent                                 AS poDetail_po_vendor_bump_percent,
            po.po_vendor_freight_calc_method_type_id                  AS poDetail_po_vendor_freight_calc_method_type_id,
            po.po_vendor_freight_percent                              AS poDetail_po_vendor_freight_percent,
            po.po_vendor_freight_amount                               AS poDetail_po_vendor_freight_amount,
            po.po_vendor_charge_inventory_tax_1                       AS poDetail_po_vendor_charge_inventory_tax_1,
            po.po_vendor_charge_inventory_tax_2                       AS poDetail_po_vendor_charge_inventory_tax_2,
            po.po_vendor_charge_inventory_tax_3                       AS poDetail_po_vendor_charge_inventory_tax_3,
            po.po_vendor_charge_inventory_tax_4                       AS poDetail_po_vendor_charge_inventory_tax_4,
            po.po_vendor_federal_id_number_verification               AS poDetail_po_vendor_federal_id_number_verification,
            po.po_vendor_email_address                                AS poDetail_po_vendor_email_address,
            po.po_vendor_purchase_order_submit_email                  AS poDetail_po_vendor_purchase_order_submit_email,
            po.po_vendor_allow_drop_ship_to_customer                  AS poDetail_po_vendor_allow_drop_ship_to_customer,
            po.po_vendor_auto_submit_purchase_order                   AS poDetail_po_vendor_auto_submit_purchase_order,
            po.po_vendor_note                                         AS poDetail_po_vendor_note,
            po.po_vendor_phone_number                                 AS poDetail_po_vendor_phone_number,
            po.po_vendor_comp_id                                      AS poDetail_po_vendor_comp_id,
            po.po_vendor_comp_time_created                            AS poDetail_po_vendor_comp_time_created,
            po.po_vendor_comp_time_updated                            AS poDetail_po_vendor_comp_time_updated,
            po.po_vendor_comp_name                                    AS poDetail_po_vendor_comp_name,
            po.po_vendor_comp_doing_business_as                       AS poDetail_po_vendor_comp_doing_business_as,
            po.po_vendor_comp_client_code                             AS poDetail_po_vendor_comp_client_code,
            po.po_vendor_comp_client_id                               AS poDetail_po_vendor_comp_client_id,
            po.po_vendor_comp_dataset_code                            AS poDetail_po_vendor_comp_dataset_code,
            po.po_vendor_comp_federal_id_number                       AS poDetail_po_vendor_comp_federal_id_number,
            po.po_vendor_comp_address_id                              AS poDetail_po_vendor_comp_address_id,
            po.po_vendor_comp_address_name                            AS poDetail_po_vendor_comp_address_name,
            po.po_vendor_comp_address_address1                        AS poDetail_po_vendor_comp_address_address1,
            po.po_vendor_comp_address_address2                        AS poDetail_po_vendor_comp_address_address2,
            po.po_vendor_comp_address_city                            AS poDetail_po_vendor_comp_address_city,
            po.po_vendor_comp_address_state                           AS poDetail_po_vendor_comp_address_state,
            po.po_vendor_comp_address_postal_code                     AS poDetail_po_vendor_comp_address_postal_code,
            po.po_vendor_comp_address_latitude                        AS poDetail_po_vendor_comp_address_latitude,
            po.po_vendor_comp_address_longitude                       AS poDetail_po_vendor_comp_address_longitude,
            po.po_vendor_comp_address_country                         AS poDetail_po_vendor_comp_address_country,
            po.po_vendor_comp_address_county                          AS poDetail_po_vendor_comp_address_county,
            po.po_vendor_comp_address_phone                           AS poDetail_po_vendor_comp_address_phone,
            po.po_vendor_comp_address_fax                             AS poDetail_po_vendor_comp_address_fax,
            po.po_vendor_onboard_id                                   AS poDetail_po_vendor_onboard_id,
            po.po_vendor_onboard_value                                AS poDetail_po_vendor_onboard_value,
            po.po_vendor_onboard_description                          AS poDetail_po_vendor_onboard_description,
            po.po_vendor_onboard_localization_code                    AS poDetail_po_vendor_onboard_localization_code,
            po.po_vendor_method_id                                    AS poDetail_po_vendor_method_id,
            po.po_vendor_method_value                                 AS poDetail_po_vendor_method_value,
            po.po_vendor_method_description                           AS poDetail_po_vendor_method_description,
            po.po_vendor_method_localization_code                     AS poDetail_po_vendor_method_localization_code,
            po.po_vendor_address_id                                   AS poDetail_po_vendor_address_id,
            po.po_vendor_address_time_created                         AS poDetail_po_vendor_address_time_created,
            po.po_vendor_address_time_updated                         AS poDetail_po_vendor_address_time_updated,
            po.po_vendor_address_number                               AS poDetail_po_vendor_address_number,
            po.po_vendor_address_name                                 AS poDetail_po_vendor_address_name,
            po.po_vendor_address_address1                             AS poDetail_po_vendor_address_address1,
            po.po_vendor_address_address2                             AS poDetail_po_vendor_address_address2,
            po.po_vendor_address_city                                 AS poDetail_po_vendor_address_city,
            po.po_vendor_address_state                                AS poDetail_po_vendor_address_state,
            po.po_vendor_address_postal_code                          AS poDetail_po_vendor_address_postal_code,
            po.po_vendor_address_latitude                             AS poDetail_po_vendor_address_latitude,
            po.po_vendor_address_longitude                            AS poDetail_po_vendor_address_longitude,
            po.po_vendor_address_country                              AS poDetail_po_vendor_address_country,
            po.po_vendor_address_county                               AS poDetail_po_vendor_address_county,
            po.po_vendor_address_phone                                AS poDetail_po_vendor_address_phone,
            po.po_vendor_address_fax                                  AS poDetail_po_vendor_address_fax,
            po.po_vendor_vpt_id                                       AS poDetail_po_vendor_vpt_id,
            po.po_vendor_vpt_time_created                             AS poDetail_po_vendor_vpt_time_created,
            po.po_vendor_vpt_time_updated                             AS poDetail_po_vendor_vpt_time_updated,
            po.po_vendor_vpt_company_id                               AS poDetail_po_vendor_vpt_company_id,
            po.po_vendor_vpt_description                              AS poDetail_po_vendor_vpt_description,
            po.po_vendor_vpt_number                                   AS poDetail_po_vendor_vpt_number,
            po.po_vendor_vpt_number_of_payments                       AS poDetail_po_vendor_vpt_number_of_payments,
            po.po_vendor_vpt_discount_month                           AS poDetail_po_vendor_vpt_discount_month,
            po.po_vendor_vpt_discount_days                            AS poDetail_po_vendor_vpt_discount_days,
            po.po_vendor_vpt_discount_percent                         AS poDetail_po_vendor_vpt_discount_percent,
            po.po_vendor_shipVia_id                                   AS poDetail_po_vendor_shipVia_id,
            po.po_vendor_shipVia_time_created                         AS poDetail_po_vendor_shipVia_time_created,
            po.po_vendor_shipVia_time_updated                         AS poDetail_po_vendor_shipVia_time_updated,
            po.po_vendor_shipVia_description                          AS poDetail_po_vendor_shipVia_description,
            po.po_vendor_shipVia_number                               AS poDetail_po_vendor_shipVia_number,
            po.po_vendor_vgrp_id                                      AS poDetail_po_vendor_vgrp_id,
            po.po_vendor_vgrp_time_created                            AS poDetail_po_vendor_vgrp_time_created,
            po.po_vendor_vgrp_time_updated                            AS poDetail_po_vendor_vgrp_time_updated,
            po.po_vendor_vgrp_company_id                              AS poDetail_po_vendor_vgrp_company_id,
            po.po_vendor_vgrp_value                                   AS poDetail_po_vendor_vgrp_value,
            po.po_vendor_vgrp_description                             AS poDetail_po_vendor_vgrp_description,
            po.po_statusType_id                                       AS poDetail_po_statusType_id,
            po.po_statusType_value                                    AS poDetail_po_statusType_value,
            po.po_statusType_description                              AS poDetail_po_statusType_description,
            po.po_statusType_localization_code                        AS poDetail_po_statusType_localization_code,
            po.po_type_id                                             AS poDetail_po_type_id,
            po.po_type_value                                          AS poDetail_po_type_value,
            po.po_type_description                                    AS poDetail_po_type_description,
            po.po_type_localization_code                              AS poDetail_po_type_localization_code,
            po.po_freightOnboardType_id                               AS poDetail_po_freightOnboardType_id,
            po.po_freightOnboardType_value                            AS poDetail_po_freightOnboardType_value,
            po.po_freightOnboardType_description                      AS poDetail_po_freightOnboardType_description,
            po.po_freightOnboardType_localization_code                AS poDetail_po_freightOnboardType_localization_code,
            po.po_freightTermType_id                                  AS poDetail_po_freightTermType_id,
            po.po_freightTermType_value                               AS poDetail_po_freightTermType_value,
            po.po_freightTermType_description                         AS poDetail_po_freightTermType_description,
            po.po_freightTermType_localization_code                   AS poDetail_po_freightTermType_localization_code,
            po.po_shipLocType_id                                      AS poDetail_po_shipLocType_id,
            po.po_shipLocType_value                                   AS poDetail_po_shipLocType_value,
            po.po_shipLocType_description                             AS poDetail_po_shipLocType_description,
            po.po_shipLocType_localization_code                       AS poDetail_po_shipLocType_localization_code,
            po.po_approvedBy_id                                       AS poDetail_po_approvedBy_id,
            po.po_approvedBy_number                                   AS poDetail_po_approvedBy_number,
            po.po_approvedBy_last_name                                AS poDetail_po_approvedBy_last_name,
            po.po_approvedBy_first_name_mi                            AS poDetail_po_approvedBy_first_name_mi,
            po.po_approvedBy_type                                     AS poDetail_po_approvedBy_type,
            po.po_approvedBy_pass_code                                AS poDetail_po_approvedBy_pass_code,
            po.po_approvedBy_active                                   AS poDetail_po_approvedBy_active,
            po.po_approvedBy_department                               AS poDetail_po_approvedBy_department,
            po.po_approvedBy_cynergi_system_admin                     AS poDetail_po_approvedBy_cynergi_system_admin,
            po.po_approvedBy_alternative_store_indicator              AS poDetail_po_approvedBy_alternative_store_indicator,
            po.po_approvedBy_alternative_area                         AS poDetail_po_approvedBy_alternative_area,
            po.po_approvedBy_store_id                                 AS poDetail_po_approvedBy_store_id,
            po.po_approvedBy_store_number                             AS poDetail_po_approvedBy_store_number,
            po.po_approvedBy_store_name                               AS poDetail_po_approvedBy_store_name,
            po.po_approvedBy_dept_id                                  AS poDetail_po_approvedBy_dept_id,
            po.po_approvedBy_dept_code                                AS poDetail_po_approvedBy_dept_code,
            po.po_approvedBy_dept_description                         AS poDetail_po_approvedBy_dept_description,
            po.po_approvedBy_comp_id                                  AS poDetail_po_approvedBy_comp_id,
            po.po_approvedBy_comp_time_created                        AS poDetail_po_approvedBy_comp_time_created,
            po.po_approvedBy_comp_time_updated                        AS poDetail_po_approvedBy_comp_time_updated,
            po.po_approvedBy_comp_name                                AS poDetail_po_approvedBy_comp_name,
            po.po_approvedBy_comp_doing_business_as                   AS poDetail_po_approvedBy_comp_doing_business_as,
            po.po_approvedBy_comp_client_code                         AS poDetail_po_approvedBy_comp_client_code,
            po.po_approvedBy_comp_client_id                           AS poDetail_po_approvedBy_comp_client_id,
            po.po_approvedBy_comp_dataset_code                        AS poDetail_po_approvedBy_comp_dataset_code,
            po.po_approvedBy_comp_federal_id_number                   AS poDetail_po_approvedBy_comp_federal_id_number,
            po.po_approvedBy_comp_address_id                          AS poDetail_po_approvedBy_comp_address_id,
            po.po_approvedBy_comp_address_name                        AS poDetail_po_approvedBy_comp_address_name,
            po.po_approvedBy_comp_address_address1                    AS poDetail_po_approvedBy_comp_address_address1,
            po.po_approvedBy_comp_address_address2                    AS poDetail_po_approvedBy_comp_address_address2,
            po.po_approvedBy_comp_address_city                        AS poDetail_po_approvedBy_comp_address_city,
            po.po_approvedBy_comp_address_state                       AS poDetail_po_approvedBy_comp_address_state,
            po.po_approvedBy_comp_address_postal_code                 AS poDetail_po_approvedBy_comp_address_postal_code,
            po.po_approvedBy_comp_address_latitude                    AS poDetail_po_approvedBy_comp_address_latitude,
            po.po_approvedBy_comp_address_longitude                   AS poDetail_po_approvedBy_comp_address_longitude,
            po.po_approvedBy_comp_address_country                     AS poDetail_po_approvedBy_comp_address_country,
            po.po_approvedBy_comp_address_county                      AS poDetail_po_approvedBy_comp_address_county,
            po.po_approvedBy_comp_address_phone                       AS poDetail_po_approvedBy_comp_address_phone,
            po.po_approvedBy_comp_address_fax                         AS poDetail_po_approvedBy_comp_address_fax,
            po.po_purchaseAgent_id                                    AS poDetail_po_purchaseAgent_id,
            po.po_purchaseAgent_number                                AS poDetail_po_purchaseAgent_number,
            po.po_purchaseAgent_last_name                             AS poDetail_po_purchaseAgent_last_name,
            po.po_purchaseAgent_first_name_mi                         AS poDetail_po_purchaseAgent_first_name_mi,
            po.po_purchaseAgent_type                                  AS poDetail_po_purchaseAgent_type,
            po.po_purchaseAgent_pass_code                             AS poDetail_po_purchaseAgent_pass_code,
            po.po_purchaseAgent_active                                AS poDetail_po_purchaseAgent_active,
            po.po_purchaseAgent_department                            AS poDetail_po_purchaseAgent_department,
            po.po_purchaseAgent_cynergi_system_admin                  AS poDetail_po_purchaseAgent_cynergi_system_admin,
            po.po_purchaseAgent_alternative_store_indicator           AS poDetail_po_purchaseAgent_alternative_store_indicator,
            po.po_purchaseAgent_alternative_area                      AS poDetail_po_purchaseAgent_alternative_area,
            po.po_purchaseAgent_store_id                              AS poDetail_po_purchaseAgent_store_id,
            po.po_purchaseAgent_store_number                          AS poDetail_po_purchaseAgent_store_number,
            po.po_purchaseAgent_store_name                            AS poDetail_po_purchaseAgent_store_name,
            po.po_purchaseAgent_dept_id                               AS poDetail_po_purchaseAgent_dept_id,
            po.po_purchaseAgent_dept_code                             AS poDetail_po_purchaseAgent_dept_code,
            po.po_purchaseAgent_dept_description                      AS poDetail_po_purchaseAgent_dept_description,
            po.po_purchaseAgent_comp_id                               AS poDetail_po_purchaseAgent_comp_id,
            po.po_purchaseAgent_comp_time_created                     AS poDetail_po_purchaseAgent_comp_time_created,
            po.po_purchaseAgent_comp_time_updated                     AS poDetail_po_purchaseAgent_comp_time_updated,
            po.po_purchaseAgent_comp_name                             AS poDetail_po_purchaseAgent_comp_name,
            po.po_purchaseAgent_comp_doing_business_as                AS poDetail_po_purchaseAgent_comp_doing_business_as,
            po.po_purchaseAgent_comp_client_code                      AS poDetail_po_purchaseAgent_comp_client_code,
            po.po_purchaseAgent_comp_client_id                        AS poDetail_po_purchaseAgent_comp_client_id,
            po.po_purchaseAgent_comp_dataset_code                     AS poDetail_po_purchaseAgent_comp_dataset_code,
            po.po_purchaseAgent_comp_federal_id_number                AS poDetail_po_purchaseAgent_comp_federal_id_number,
            po.po_purchaseAgent_comp_address_id                       AS poDetail_po_purchaseAgent_comp_address_id,
            po.po_purchaseAgent_comp_address_name                     AS poDetail_po_purchaseAgent_comp_address_name,
            po.po_purchaseAgent_comp_address_address1                 AS poDetail_po_purchaseAgent_comp_address_address1,
            po.po_purchaseAgent_comp_address_address2                 AS poDetail_po_purchaseAgent_comp_address_address2,
            po.po_purchaseAgent_comp_address_city                     AS poDetail_po_purchaseAgent_comp_address_city,
            po.po_purchaseAgent_comp_address_state                    AS poDetail_po_purchaseAgent_comp_address_state,
            po.po_purchaseAgent_comp_address_postal_code              AS poDetail_po_purchaseAgent_comp_address_postal_code,
            po.po_purchaseAgent_comp_address_latitude                 AS poDetail_po_purchaseAgent_comp_address_latitude,
            po.po_purchaseAgent_comp_address_longitude                AS poDetail_po_purchaseAgent_comp_address_longitude,
            po.po_purchaseAgent_comp_address_country                  AS poDetail_po_purchaseAgent_comp_address_country,
            po.po_purchaseAgent_comp_address_county                   AS poDetail_po_purchaseAgent_comp_address_county,
            po.po_purchaseAgent_comp_address_phone                    AS poDetail_po_purchaseAgent_comp_address_phone,
            po.po_purchaseAgent_comp_address_fax                      AS poDetail_po_purchaseAgent_comp_address_fax,
            po.po_shipVia_id                                          AS poDetail_po_shipVia_id,
            po.po_shipVia_time_created                                AS poDetail_po_shipVia_time_created,
            po.po_shipVia_time_updated                                AS poDetail_po_shipVia_time_updated,
            po.po_shipVia_description                                 AS poDetail_po_shipVia_description,
            po.po_shipVia_number                                      AS poDetail_po_shipVia_number,
            po.po_shipVia_comp_id                                     AS poDetail_po_shipVia_comp_id,
            po.po_shipVia_comp_name                                   AS poDetail_po_shipVia_comp_name,
            po.po_shipVia_comp_doing_business_as                      AS poDetail_po_shipVia_comp_doing_business_as,
            po.po_shipVia_comp_client_code                            AS poDetail_po_shipVia_comp_client_code,
            po.po_shipVia_comp_client_id                              AS poDetail_po_shipVia_comp_client_id,
            po.po_shipVia_comp_dataset_code                           AS poDetail_po_shipVia_comp_dataset_code,
            po.po_shipVia_comp_federal_id_number                      AS poDetail_po_shipVia_comp_federal_id_number,
            po.po_shipVia_address_id                                  AS poDetail_po_shipVia_address_id,
            po.po_shipVia_address_name                                AS poDetail_po_shipVia_address_name,
            po.po_shipVia_address_address1                            AS poDetail_po_shipVia_address_address1,
            po.po_shipVia_address_address2                            AS poDetail_po_shipVia_address_address2,
            po.po_shipVia_address_city                                AS poDetail_po_shipVia_address_city,
            po.po_shipVia_address_state                               AS poDetail_po_shipVia_address_state,
            po.po_shipVia_address_postal_code                         AS poDetail_po_shipVia_address_postal_code,
            po.po_shipVia_address_latitude                            AS poDetail_po_shipVia_address_latitude,
            po.po_shipVia_address_longitude                           AS poDetail_po_shipVia_address_longitude,
            po.po_shipVia_address_country                             AS poDetail_po_shipVia_address_country,
            po.po_shipVia_address_county                              AS poDetail_po_shipVia_address_county,
            po.po_shipVia_address_phone                               AS poDetail_po_shipVia_address_phone,
            po.po_shipVia_address_fax                                 AS poDetail_po_shipVia_address_fax,
            po.po_shipTo_id                                           AS poDetail_po_shipTo_id,
            po.po_shipTo_number                                       AS poDetail_po_shipTo_number,
            po.po_shipTo_name                                         AS poDetail_po_shipTo_name,
            po.po_shipTo_dataset                                      AS poDetail_po_shipTo_dataset,
            po.po_paymentTermType_vpt_id                              AS poDetail_po_paymentTermType_vpt_id,
            po.po_paymentTermType_vpt_time_created                    AS poDetail_po_paymentTermType_vpt_time_created,
            po.po_paymentTermType_vpt_time_updated                    AS poDetail_po_paymentTermType_vpt_time_updated,
            po.po_paymentTermType_vpt_company_id                      AS poDetail_po_paymentTermType_vpt_company_id,
            po.po_paymentTermType_vpt_description                     AS poDetail_po_paymentTermType_vpt_description,
            po.po_paymentTermType_vpt_number                          AS poDetail_po_paymentTermType_vpt_number,
            po.po_paymentTermType_vpt_number_of_payments              AS poDetail_po_paymentTermType_vpt_number_of_payments,
            po.po_paymentTermType_vpt_discount_month                  AS poDetail_po_paymentTermType_vpt_discount_month,
            po.po_paymentTermType_vpt_discount_days                   AS poDetail_po_paymentTermType_vpt_discount_days,
            po.po_paymentTermType_vpt_discount_percent                AS poDetail_po_paymentTermType_vpt_discount_percent,
            po.po_paymentTermType_comp_id                             AS poDetail_po_paymentTermType_comp_id,
            po.po_paymentTermType_comp_time_created                   AS poDetail_po_paymentTermType_comp_time_created,
            po.po_paymentTermType_comp_time_updated                   AS poDetail_po_paymentTermType_comp_time_updated,
            po.po_paymentTermType_comp_name                           AS poDetail_po_paymentTermType_comp_name,
            po.po_paymentTermType_comp_doing_business_as              AS poDetail_po_paymentTermType_comp_doing_business_as,
            po.po_paymentTermType_comp_client_code                    AS poDetail_po_paymentTermType_comp_client_code,
            po.po_paymentTermType_comp_client_id                      AS poDetail_po_paymentTermType_comp_client_id,
            po.po_paymentTermType_comp_dataset_code                   AS poDetail_po_paymentTermType_comp_dataset_code,
            po.po_paymentTermType_comp_federal_id_number              AS poDetail_po_paymentTermType_comp_federal_id_number,
            po.po_paymentTermType_address_id                          AS poDetail_po_paymentTermType_address_id,
            po.po_paymentTermType_address_name                        AS poDetail_po_paymentTermType_address_name,
            po.po_paymentTermType_address_address1                    AS poDetail_po_paymentTermType_address_address1,
            po.po_paymentTermType_address_address2                    AS poDetail_po_paymentTermType_address_address2,
            po.po_paymentTermType_address_city                        AS poDetail_po_paymentTermType_address_city,
            po.po_paymentTermType_address_state                       AS poDetail_po_paymentTermType_address_state,
            po.po_paymentTermType_address_postal_code                 AS poDetail_po_paymentTermType_address_postal_code,
            po.po_paymentTermType_address_latitude                    AS poDetail_po_paymentTermType_address_latitude,
            po.po_paymentTermType_address_longitude                   AS poDetail_po_paymentTermType_address_longitude,
            po.po_paymentTermType_address_country                     AS poDetail_po_paymentTermType_address_country,
            po.po_paymentTermType_address_county                      AS poDetail_po_paymentTermType_address_county,
            po.po_paymentTermType_address_phone                       AS poDetail_po_paymentTermType_address_phone,
            po.po_paymentTermType_address_fax                         AS poDetail_po_paymentTermType_address_fax,
            po.po_paymentTermType_vpts_id                             AS poDetail_po_paymentTermType_vpts_id,
            po.po_paymentTermType_vpts_time_created                   AS poDetail_po_paymentTermType_vpts_time_created,
            po.po_paymentTermType_vpts_time_updated                   AS poDetail_po_paymentTermType_vpts_time_updated,
            po.po_paymentTermType_vpts_payment_term_id                AS poDetail_po_paymentTermType_vpts_payment_term_id,
            po.po_paymentTermType_vpts_due_month                      AS poDetail_po_paymentTermType_vpts_due_month,
            po.po_paymentTermType_vpts_due_days                       AS poDetail_po_paymentTermType_vpts_due_days,
            po.po_paymentTermType_vpts_due_percent                    AS poDetail_po_paymentTermType_vpts_due_percent,
            po.po_paymentTermType_vpts_schedule_order_number          AS poDetail_po_paymentTermType_vpts_schedule_order_number,
            po.po_exceptionIndType_id                                 AS poDetail_po_exceptionIndType_id,
            po.po_exceptionIndType_value                              AS poDetail_po_exceptionIndType_value,
            po.po_exceptionIndType_description                        AS poDetail_po_exceptionIndType_description,
            po.po_exceptionIndType_localization_code                  AS poDetail_po_exceptionIndType_localization_code,
            po.po_vendorSubmittedEmp_id                               AS poDetail_po_vendorSubmittedEmp_id,
            po.po_vendorSubmittedEmp_number                           AS poDetail_po_vendorSubmittedEmp_number,
            po.po_vendorSubmittedEmp_last_name                        AS poDetail_po_vendorSubmittedEmp_last_name,
            po.po_vendorSubmittedEmp_first_name_mi                    AS poDetail_po_vendorSubmittedEmp_first_name_mi,
            po.po_vendorSubmittedEmp_type                             AS poDetail_po_vendorSubmittedEmp_type,
            po.po_vendorSubmittedEmp_pass_code                        AS poDetail_po_vendorSubmittedEmp_pass_code,
            po.po_vendorSubmittedEmp_active                           AS poDetail_po_vendorSubmittedEmp_active,
            po.po_vendorSubmittedEmp_department                       AS poDetail_po_vendorSubmittedEmp_department,
            po.po_vendorSubmittedEmp_cynergi_system_admin             AS poDetail_po_vendorSubmittedEmp_cynergi_system_admin,
            po.po_vendorSubmittedEmp_alternative_store_indicator      AS poDetail_po_vendorSubmittedEmp_alternative_store_indicator,
            po.po_vendorSubmittedEmp_alternative_area                 AS poDetail_po_vendorSubmittedEmp_alternative_area,
            po.po_vendorSubmittedEmp_store_id                         AS poDetail_po_vendorSubmittedEmp_store_id,
            po.po_vendorSubmittedEmp_store_number                     AS poDetail_po_vendorSubmittedEmp_store_number,
            po.po_vendorSubmittedEmp_store_name                       AS poDetail_po_vendorSubmittedEmp_store_name,
            po.po_vendorSubmittedEmp_dept_id                          AS poDetail_po_vendorSubmittedEmp_dept_id,
            po.po_vendorSubmittedEmp_dept_code                        AS poDetail_po_vendorSubmittedEmp_dept_code,
            po.po_vendorSubmittedEmp_dept_description                 AS poDetail_po_vendorSubmittedEmp_dept_description,
            po.po_vendorSubmittedEmp_comp_id                          AS poDetail_po_vendorSubmittedEmp_comp_id,
            po.po_vendorSubmittedEmp_comp_time_created                AS poDetail_po_vendorSubmittedEmp_comp_time_created,
            po.po_vendorSubmittedEmp_comp_time_updated                AS poDetail_po_vendorSubmittedEmp_comp_time_updated,
            po.po_vendorSubmittedEmp_comp_name                        AS poDetail_po_vendorSubmittedEmp_comp_name,
            po.po_vendorSubmittedEmp_comp_doing_business_as           AS poDetail_po_vendorSubmittedEmp_comp_doing_business_as,
            po.po_vendorSubmittedEmp_comp_client_code                 AS poDetail_po_vendorSubmittedEmp_comp_client_code,
            po.po_vendorSubmittedEmp_comp_client_id                   AS poDetail_po_vendorSubmittedEmp_comp_client_id,
            po.po_vendorSubmittedEmp_comp_dataset_code                AS poDetail_po_vendorSubmittedEmp_comp_dataset_code,
            po.po_vendorSubmittedEmp_comp_federal_id_number           AS poDetail_po_vendorSubmittedEmp_comp_federal_id_number,
            po.po_vendorSubmittedEmp_comp_address_id                  AS poDetail_po_vendorSubmittedEmp_comp_address_id,
            po.po_vendorSubmittedEmp_comp_address_name                AS poDetail_po_vendorSubmittedEmp_comp_address_name,
            po.po_vendorSubmittedEmp_comp_address_address1            AS poDetail_po_vendorSubmittedEmp_comp_address_address1,
            po.po_vendorSubmittedEmp_comp_address_address2            AS poDetail_po_vendorSubmittedEmp_comp_address_address2,
            po.po_vendorSubmittedEmp_comp_address_city                AS poDetail_po_vendorSubmittedEmp_comp_address_city,
            po.po_vendorSubmittedEmp_comp_address_state               AS poDetail_po_vendorSubmittedEmp_comp_address_state,
            po.po_vendorSubmittedEmp_comp_address_postal_code         AS poDetail_po_vendorSubmittedEmp_comp_address_postal_code,
            po.po_vendorSubmittedEmp_comp_address_latitude            AS poDetail_po_vendorSubmittedEmp_comp_address_latitude,
            po.po_vendorSubmittedEmp_comp_address_longitude           AS poDetail_po_vendorSubmittedEmp_comp_address_longitude,
            po.po_vendorSubmittedEmp_comp_address_country             AS poDetail_po_vendorSubmittedEmp_comp_address_country,
            po.po_vendorSubmittedEmp_comp_address_county              AS poDetail_po_vendorSubmittedEmp_comp_address_county,
            po.po_vendorSubmittedEmp_comp_address_phone               AS poDetail_po_vendorSubmittedEmp_comp_address_phone,
            po.po_vendorSubmittedEmp_comp_address_fax                 AS poDetail_po_vendorSubmittedEmp_comp_address_fax,
            vendor.v_id                                               AS poDetail_vendor_id,
            vendor.v_time_created                                     AS poDetail_vendor_time_created,
            vendor.v_time_updated                                     AS poDetail_vendor_time_updated,
            vendor.v_company_id                                       AS poDetail_vendor_company_id,
            vendor.v_number                                           AS poDetail_vendor_number,
            vendor.v_name                                             AS poDetail_vendor_name,
            vendor.v_address_id                                       AS poDetail_vendor_address_id,
            vendor.v_account_number                                   AS poDetail_vendor_account_number,
            vendor.v_pay_to_id                                        AS poDetail_vendor_pay_to_id,
            vendor.v_freight_on_board_type_id                         AS poDetail_vendor_freight_on_board_type_id,
            vendor.v_vendor_payment_term_id                           AS poDetail_vendor_vendor_payment_term_id,
            vendor.v_normal_days                                      AS poDetail_vendor_normal_days,
            vendor.v_return_policy                                    AS poDetail_vendor_return_policy,
            vendor.v_ship_via_id                                      AS poDetail_vendor_ship_via_id,
            vendor.v_vendor_group_id                                  AS poDetail_vendor_group_id,
            vendor.v_minimum_quantity                                 AS poDetail_vendor_minimum_quantity,
            vendor.v_minimum_amount                                   AS poDetail_vendor_minimum_amount,
            vendor.v_free_ship_quantity                               AS poDetail_vendor_free_ship_quantity,
            vendor.v_free_ship_amount                                 AS poDetail_vendor_free_ship_amount,
            vendor.v_vendor_1099                                      AS poDetail_vendor_vendor_1099,
            vendor.v_federal_id_number                                AS poDetail_vendor_federal_id_number,
            vendor.v_sales_representative_name                        AS poDetail_vendor_sales_representative_name,
            vendor.v_sales_representative_fax                         AS poDetail_vendor_sales_representative_fax,
            vendor.v_separate_check                                   AS poDetail_vendor_separate_check,
            vendor.v_bump_percent                                     AS poDetail_vendor_bump_percent,
            vendor.v_freight_calc_method_type_id                      AS poDetail_vendor_freight_calc_method_type_id,
            vendor.v_freight_percent                                  AS poDetail_vendor_freight_percent,
            vendor.v_freight_amount                                   AS poDetail_vendor_freight_amount,
            vendor.v_charge_inventory_tax_1                           AS poDetail_vendor_charge_inventory_tax_1,
            vendor.v_charge_inventory_tax_2                           AS poDetail_vendor_charge_inventory_tax_2,
            vendor.v_charge_inventory_tax_3                           AS poDetail_vendor_charge_inventory_tax_3,
            vendor.v_charge_inventory_tax_4                           AS poDetail_vendor_charge_inventory_tax_4,
            vendor.v_federal_id_number_verification                   AS poDetail_vendor_federal_id_number_verification,
            vendor.v_email_address                                    AS poDetail_vendor_email_address,
            vendor.v_purchase_order_submit_email                      AS poDetail_vendor_purchase_order_submit_email,
            vendor.v_allow_drop_ship_to_customer                      AS poDetail_vendor_allow_drop_ship_to_customer,
            vendor.v_auto_submit_purchase_order                       AS poDetail_vendor_auto_submit_purchase_order,
            vendor.v_note                                             AS poDetail_vendor_note,
            vendor.v_phone_number                                     AS poDetail_vendor_phone_number,
            vendor.v_comp_id                                          AS poDetail_vendor_comp_id,
            vendor.v_comp_time_created                                AS poDetail_vendor_comp_time_created,
            vendor.v_comp_time_updated                                AS poDetail_vendor_comp_time_updated,
            vendor.v_comp_name                                        AS poDetail_vendor_comp_name,
            vendor.v_comp_doing_business_as                           AS poDetail_vendor_comp_doing_business_as,
            vendor.v_comp_client_code                                 AS poDetail_vendor_comp_client_code,
            vendor.v_comp_client_id                                   AS poDetail_vendor_comp_client_id,
            vendor.v_comp_dataset_code                                AS poDetail_vendor_comp_dataset_code,
            vendor.v_comp_federal_id_number                           AS poDetail_vendor_comp_federal_id_number,
            vendor.v_comp_address_id                                  AS poDetail_vendor_comp_address_id,
            vendor.v_comp_address_name                                AS poDetail_vendor_comp_address_name,
            vendor.v_comp_address_address1                            AS poDetail_vendor_comp_address_address1,
            vendor.v_comp_address_address2                            AS poDetail_vendor_comp_address_address2,
            vendor.v_comp_address_city                                AS poDetail_vendor_comp_address_city,
            vendor.v_comp_address_state                               AS poDetail_vendor_comp_address_state,
            vendor.v_comp_address_postal_code                         AS poDetail_vendor_comp_address_postal_code,
            vendor.v_comp_address_latitude                            AS poDetail_vendor_comp_address_latitude,
            vendor.v_comp_address_longitude                           AS poDetail_vendor_comp_address_longitude,
            vendor.v_comp_address_country                             AS poDetail_vendor_comp_address_country,
            vendor.v_comp_address_county                              AS poDetail_vendor_comp_address_county,
            vendor.v_comp_address_phone                               AS poDetail_vendor_comp_address_phone,
            vendor.v_comp_address_fax                                 AS poDetail_vendor_comp_address_fax,
            vendor.v_onboard_id                                       AS poDetail_vendor_onboard_id,
            vendor.v_onboard_value                                    AS poDetail_vendor_onboard_value,
            vendor.v_onboard_description                              AS poDetail_vendor_onboard_description,
            vendor.v_onboard_localization_code                        AS poDetail_vendor_onboard_localization_code,
            vendor.v_method_id                                        AS poDetail_vendor_method_id,
            vendor.v_method_value                                     AS poDetail_vendor_method_value,
            vendor.v_method_description                               AS poDetail_vendor_method_description,
            vendor.v_method_localization_code                         AS poDetail_vendor_method_localization_code,
            vendor.v_address_id                                       AS poDetail_vendor_address_id,
            vendor.v_address_time_created                             AS poDetail_vendor_address_time_created,
            vendor.v_address_time_updated                             AS poDetail_vendor_address_time_updated,
            vendor.v_address_number                                   AS poDetail_vendor_address_number,
            vendor.v_address_name                                     AS poDetail_vendor_address_name,
            vendor.v_address_address1                                 AS poDetail_vendor_address_address1,
            vendor.v_address_address2                                 AS poDetail_vendor_address_address2,
            vendor.v_address_city                                     AS poDetail_vendor_address_city,
            vendor.v_address_state                                    AS poDetail_vendor_address_state,
            vendor.v_address_postal_code                              AS poDetail_vendor_address_postal_code,
            vendor.v_address_latitude                                 AS poDetail_vendor_address_latitude,
            vendor.v_address_longitude                                AS poDetail_vendor_address_longitude,
            vendor.v_address_country                                  AS poDetail_vendor_address_country,
            vendor.v_address_county                                   AS poDetail_vendor_address_county,
            vendor.v_address_phone                                    AS poDetail_vendor_address_phone,
            vendor.v_address_fax                                      AS poDetail_vendor_address_fax,
            vendor.v_vpt_id                                           AS poDetail_vendor_vpt_id,
            vendor.v_vpt_time_created                                 AS poDetail_vendor_vpt_time_created,
            vendor.v_vpt_time_updated                                 AS poDetail_vendor_vpt_time_updated,
            vendor.v_vpt_company_id                                   AS poDetail_vendor_vpt_company_id,
            vendor.v_vpt_description                                  AS poDetail_vendor_vpt_description,
            vendor.v_vpt_number                                       AS poDetail_vendor_vpt_number,
            vendor.v_vpt_number_of_payments                           AS poDetail_vendor_vpt_number_of_payments,
            vendor.v_vpt_discount_month                               AS poDetail_vendor_vpt_discount_month,
            vendor.v_vpt_discount_days                                AS poDetail_vendor_vpt_discount_days,
            vendor.v_vpt_discount_percent                             AS poDetail_vendor_vpt_discount_percent,
            vendor.v_shipVia_id                                       AS poDetail_vendor_shipVia_id,
            vendor.v_shipVia_time_created                             AS poDetail_vendor_shipVia_time_created,
            vendor.v_shipVia_time_updated                             AS poDetail_vendor_shipVia_time_updated,
            vendor.v_shipVia_description                              AS poDetail_vendor_shipVia_description,
            vendor.v_shipVia_number                                   AS poDetail_vendor_shipVia_number,
            vendor.v_vgrp_id                                          AS poDetail_vendor_vgrp_id,
            vendor.v_vgrp_time_created                                AS poDetail_vendor_vgrp_time_created,
            vendor.v_vgrp_time_updated                                AS poDetail_vendor_vgrp_time_updated,
            vendor.v_vgrp_company_id                                  AS poDetail_vendor_vgrp_company_id,
            vendor.v_vgrp_value                                       AS poDetail_vendor_vgrp_value,
            vendor.v_vgrp_description                                 AS poDetail_vendor_vgrp_description,
            statusType.id                                             AS poDetail_statusType_id,
            statusType.value                                          AS poDetail_statusType_value,
            statusType.description                                    AS poDetail_statusType_description,
            statusType.localization_code                              AS poDetail_statusType_localization_code,
            poReqIndType.id                                           AS poDetail_poReqIndType_id,
            poReqIndType.value                                        AS poDetail_poReqIndType_value,
            poReqIndType.description                                  AS poDetail_poReqIndType_description,
            poReqIndType.localization_code                            AS poDetail_poReqIndType_localization_code,
            exceptionIndType.id                                       AS poDetail_exceptionIndType_id,
            exceptionIndType.value                                    AS poDetail_exceptionIndType_value,
            exceptionIndType.description                              AS poDetail_exceptionIndType_description,
            exceptionIndType.localization_code                        AS poDetail_exceptionIndType_localization_code,
            count(*) OVER()                                           AS total_elements
         FROM purchase_order_detail poDetail
            JOIN company comp                                                  ON poDetail.company_id = comp.id AND comp.deleted = FALSE
            JOIN purchase_order_header po                                      ON poDetail.purchase_order_header_id = po.po_id AND po.po_deleted = FALSE
            JOIN vendor                                                        ON poDetail.vendor_id = vendor.v_id
            JOIN purchase_order_status_type_domain statusType                  ON poDetail.status_type_id = statusType.id
            JOIN purchase_order_requisition_indicator_type_domain poReqIndType ON poDetail.purchase_order_requisition_indicator_type_id = poReqIndType.id
            JOIN exception_ind_type_domain exceptionIndType                    ON poDetail.exception_ind_type_id = exceptionIndType.id
      """
   }

   @ReadOnly fun findOne(id: UUID, company: CompanyEntity): PurchaseOrderDetailEntity? {
      val params = mutableMapOf<String, Any?>("id" to id, "comp_id" to company.id)
      val query = "${selectBaseQuery()}\nWHERE poDetail.id = :id AND poDetail.company_id = :comp_id AND poDetail.deleted = FALSE"

      logger.debug("Searching for PurchaseOrderDetail using {} {}", query, params)

      val found = jdbc.findFirstOrNull(query, params) { rs, _ ->
         val purchaseOrderDetail = mapRow(rs, company, "poDetail_")

         purchaseOrderDetail
      }

      logger.trace("Searching for PurchaseOrderDetail: {} resulted in {}", id, found)

      return found
   }

   @ReadOnly
   fun findAll(company: CompanyEntity, page: PageRequest): RepositoryPage<PurchaseOrderDetailEntity, PageRequest> {
      return jdbc.queryPaged(
         """
            ${selectBaseQuery()}
            WHERE poDetail.company_id = :comp_id AND poDetail.deleted = FALSE
            ORDER BY poDetail_${page.snakeSortBy()} ${page.sortDirection()}
            LIMIT :limit OFFSET :offset
         """.trimIndent(),
         mapOf(
            "comp_id" to company.id,
            "limit" to page.size(),
            "offset" to page.offset()
         ),
         page
      ) { rs, elements ->
         do {
            elements.add(mapRow(rs, company, "poDetail_"))
         } while (rs.next())
      }
   }

   @Transactional
   fun insert(entity: PurchaseOrderDetailEntity, company: CompanyEntity): PurchaseOrderDetailEntity {
      logger.debug("Inserting PurchaseOrderDetail {}", entity)

      return jdbc.insertReturning(
         """
         INSERT INTO purchase_order_detail(
            number,
            purchase_order_header_id,
            company_id,
            itemfile_number_sfk,
            order_quantity,
            received_quantity,
            cost,
            message,
            color_id_sfk,
            fabric_id_sfk,
            cancelled_quantity,
            cancelled_temp_quantity,
            ship_to_id_sfk,
            required_date,
            date_ordered,
            freight_per_item,
            temp_quantity_to_receive,
            vendor_id,
            last_received_date,
            landed_cost,
            status_type_id,
            purchase_order_requisition_indicator_type_id,
            exception_ind_type_id,
            converted_purchase_order_number,
            approved_ind
         )
         VALUES (
            :number,
            :purchase_order_header_id,
            :company_id,
            :itemfile_number_sfk,
            :order_quantity,
            :received_quantity,
            :cost,
            :message,
            :color_id_sfk,
            :fabric_id_sfk,
            :cancelled_quantity,
            :cancelled_temp_quantity,
            :ship_to_id_sfk,
            :required_date,
            :date_ordered,
            :freight_per_item,
            :temp_quantity_to_receive,
            :vendor_id,
            :last_received_date,
            :landed_cost,
            :status_type_id,
            :purchase_order_requisition_indicator_type_id,
            :exception_ind_type_id,
            :converted_purchase_order_number,
            :approved_ind
         )
         RETURNING
            *
         """.trimIndent(),
         mapOf(
            "number" to entity.number,
            "purchase_order_header_id" to entity.purchaseOrder.id,
            "company_id" to company.id,
            "itemfile_number_sfk" to entity.itemfileNumber,
            "order_quantity" to entity.orderQuantity,
            "received_quantity" to entity.receivedQuantity,
            "cost" to entity.cost,
            "message" to entity.message,
            "color_id_sfk" to entity.color,
            "fabric_id_sfk" to entity.fabric,
            "cancelled_quantity" to entity.cancelledQuantity,
            "cancelled_temp_quantity" to entity.cancelledTempQuantity,
            "ship_to_id_sfk" to entity.shipTo.myId(),
            "required_date" to entity.requiredDate,
            "date_ordered" to entity.dateOrdered,
            "freight_per_item" to entity.freightPerItem,
            "temp_quantity_to_receive" to entity.tempQuantityToReceive,
            "vendor_id" to entity.vendor.id,
            "last_received_date" to entity.lastReceivedDate,
            "landed_cost" to entity.landedCost,
            "status_type_id" to entity.statusType.id,
            "purchase_order_requisition_indicator_type_id" to entity.purchaseOrderRequisitionIndicatorType.id,
            "exception_ind_type_id" to entity.exceptionIndicatorType.id,
            "converted_purchase_order_number" to entity.convertedPurchaseOrderNumber,
            "approved_ind" to entity.approvedIndicator
         )
      ) { rs, _ -> mapRow(rs, entity) }
   }

   @Transactional
   fun update(entity: PurchaseOrderDetailEntity, company: CompanyEntity): PurchaseOrderDetailEntity {
      logger.debug("Updating PurchaseOrderDetail {}", entity)

      return jdbc.updateReturning(
         """
            UPDATE purchase_order_detail
            SET
               number = :number,
               purchase_order_header_id = :purchase_order_header_id,
               company_id = :company_id,
               itemfile_number_sfk = :itemfile_number_sfk,
               order_quantity = :order_quantity,
               received_quantity = :received_quantity,
               cost = :cost,
               message = :message,
               color_id_sfk = :color_id_sfk,
               fabric_id_sfk = :fabric_id_sfk,
               cancelled_quantity = :cancelled_quantity,
               cancelled_temp_quantity = :cancelled_temp_quantity,
               ship_to_id_sfk = :ship_to_id_sfk,
               required_date = :required_date,
               date_ordered = :date_ordered,
               freight_per_item = :freight_per_item,
               temp_quantity_to_receive = :temp_quantity_to_receive,
               vendor_id = :vendor_id,
               last_received_date = :last_received_date,
               landed_cost = :landed_cost,
               status_type_id = :status_type_id,
               purchase_order_requisition_indicator_type_id = :purchase_order_requisition_indicator_type_id,
               exception_ind_type_id = :exception_ind_type_id,
               converted_purchase_order_number = :converted_purchase_order_number,
               approved_ind = :approved_ind
            WHERE id = :id
            RETURNING
               *
         """.trimIndent(),
         mapOf(
            "id" to entity.id,
            "number" to entity.number,
            "purchase_order_header_id" to entity.purchaseOrder.id,
            "company_id" to company.id,
            "itemfile_number_sfk" to entity.itemfileNumber,
            "order_quantity" to entity.orderQuantity,
            "received_quantity" to entity.receivedQuantity,
            "cost" to entity.cost,
            "message" to entity.message,
            "color_id_sfk" to entity.color,
            "fabric_id_sfk" to entity.fabric,
            "cancelled_quantity" to entity.cancelledQuantity,
            "cancelled_temp_quantity" to entity.cancelledTempQuantity,
            "ship_to_id_sfk" to entity.shipTo.myId(),
            "required_date" to entity.requiredDate,
            "date_ordered" to entity.dateOrdered,
            "freight_per_item" to entity.freightPerItem,
            "temp_quantity_to_receive" to entity.tempQuantityToReceive,
            "vendor_id" to entity.vendor.id,
            "last_received_date" to entity.lastReceivedDate,
            "landed_cost" to entity.landedCost,
            "status_type_id" to entity.statusType.id,
            "purchase_order_requisition_indicator_type_id" to entity.purchaseOrderRequisitionIndicatorType.id,
            "exception_ind_type_id" to entity.exceptionIndicatorType.id,
            "converted_purchase_order_number" to entity.convertedPurchaseOrderNumber,
            "approved_ind" to entity.approvedIndicator
         )
      ) { rs, _ -> mapRow(rs, entity) }
   }

   @Transactional
   fun delete(id: UUID, company: CompanyEntity) {
      logger.debug("Deleting PurchaseOrderDetail with id={}", id)

      val rowsAffected = jdbc.softDelete(
         """
         UPDATE purchase_order_detail
         SET deleted = TRUE
         WHERE id = :id AND company_id = :company_id AND deleted = FALSE
         """,
         mapOf("id" to id, "company_id" to company.id),
         "purchase_order_detail"
      )

      logger.info("Row affected {}", rowsAffected)

      if (rowsAffected == 0) {
         throw NotFoundException(id)
      }
   }

   fun mapRow(rs: ResultSet, company: CompanyEntity, columnPrefix: String = EMPTY): PurchaseOrderDetailEntity {
      return PurchaseOrderDetailEntity(
         id = rs.getUuid("${columnPrefix}id"),
         number = rs.getLong("${columnPrefix}number"),
         purchaseOrder = purchaseOrderRepository.mapRow(rs, company, "${columnPrefix}po_"),
         itemfileNumber = rs.getString("${columnPrefix}itemfile_number_sfk"),
         orderQuantity = rs.getInt("${columnPrefix}order_quantity"),
         receivedQuantity = rs.getInt("${columnPrefix}received_quantity"),
         cost = rs.getBigDecimal("${columnPrefix}cost"),
         message = rs.getString("${columnPrefix}message"),
         color = rs.getIntOrNull("${columnPrefix}color_id_sfk"),
         fabric = rs.getIntOrNull("${columnPrefix}fabric_id_sfk"),
         cancelledQuantity = rs.getIntOrNull("${columnPrefix}cancelled_quantity"),
         cancelledTempQuantity = rs.getIntOrNull("${columnPrefix}cancelled_temp_quantity"),
         shipTo = SimpleLegacyIdentifiableEntity(rs.getLong("${columnPrefix}ship_to_id_sfk")),
         requiredDate = rs.getLocalDateOrNull("${columnPrefix}required_date"),
         dateOrdered = rs.getLocalDateOrNull("${columnPrefix}date_ordered"),
         freightPerItem = rs.getBigDecimal("${columnPrefix}freight_per_item"),
         tempQuantityToReceive = rs.getIntOrNull("${columnPrefix}temp_quantity_to_receive"),
         vendor = vendorRepository.mapRow(rs, company, "${columnPrefix}vendor_"),
         lastReceivedDate = rs.getLocalDateOrNull("${columnPrefix}last_received_date"),
         landedCost = rs.getBigDecimal("${columnPrefix}landed_cost"),
         statusType = statusTypeRepository.mapRow(rs, "${columnPrefix}statusType_"),
         purchaseOrderRequisitionIndicatorType = purchaseOrderRequisitionIndicatorTypeRepository.mapRow(rs, "${columnPrefix}poReqIndType_"),
         exceptionIndicatorType = exceptionIndicatorTypeRepository.mapRow(rs, "${columnPrefix}exceptionIndType_"),
         convertedPurchaseOrderNumber = rs.getInt("${columnPrefix}converted_purchase_order_number"),
         approvedIndicator = rs.getBoolean("${columnPrefix}approved_ind")
      )
   }

   private fun mapRow(rs: ResultSet, entity: PurchaseOrderDetailEntity, columnPrefix: String = EMPTY): PurchaseOrderDetailEntity {
      return PurchaseOrderDetailEntity(
         id = rs.getUuid("${columnPrefix}id"),
         number = rs.getLong("${columnPrefix}number"),
         purchaseOrder = entity.purchaseOrder,
         itemfileNumber = rs.getString("${columnPrefix}itemfile_number_sfk"),
         orderQuantity = rs.getInt("${columnPrefix}order_quantity"),
         receivedQuantity = rs.getInt("${columnPrefix}received_quantity"),
         cost = rs.getBigDecimal("${columnPrefix}cost"),
         message = rs.getString("${columnPrefix}message"),
         color = rs.getIntOrNull("${columnPrefix}color_id_sfk"),
         fabric = rs.getIntOrNull("${columnPrefix}fabric_id_sfk"),
         cancelledQuantity = rs.getIntOrNull("${columnPrefix}cancelled_quantity"),
         cancelledTempQuantity = rs.getIntOrNull("${columnPrefix}cancelled_temp_quantity"),
         shipTo = entity.shipTo,
         requiredDate = rs.getLocalDateOrNull("${columnPrefix}required_date"),
         dateOrdered = rs.getLocalDateOrNull("${columnPrefix}date_ordered"),
         freightPerItem = rs.getBigDecimal("${columnPrefix}freight_per_item"),
         tempQuantityToReceive = rs.getIntOrNull("${columnPrefix}temp_quantity_to_receive"),
         vendor = entity.vendor,
         lastReceivedDate = rs.getLocalDateOrNull("${columnPrefix}last_received_date"),
         landedCost = rs.getBigDecimal("${columnPrefix}landed_cost"),
         statusType = entity.statusType,
         purchaseOrderRequisitionIndicatorType = entity.purchaseOrderRequisitionIndicatorType,
         exceptionIndicatorType = entity.exceptionIndicatorType,
         convertedPurchaseOrderNumber = rs.getInt("${columnPrefix}converted_purchase_order_number"),
         approvedIndicator = rs.getBoolean("${columnPrefix}approved_ind")
      )
   }
}
