version: '3.5'
networks:
  cynergideploynet:
    name: cynergideploynet
services:
  cynergitestdeploydb:
    build:
      context: ../development/db
      dockerfile: cynergitestdb.dockerfile
    tmpfs: /var/lib/postgresql/data:rw
    environment:
      - POSTGRES_DB=cynergitestdb
      - POSTGRES_PASSWORD=password
    container_name: cynergitestdeploydb
    networks:
      - cynergideploynet
  cynmid:
    build:
      context: ./cynmid
      dockerfile: cynmid.dockerfile
    volumes:
      - ../../:/home/jenkins/cynergi-middleware
      - ./gradleCache:/home/jenkins/caches
    stdin_open: true
    tty: true
    container_name: cynmid
    networks:
      - cynergideploynet
    links:
      - cynergitestdeploydb
    command: ["/home/jenkins/cynergi-middleware/support/deployment/cynmid/build-cynmid.sh"]
    #command: ["/bin/bash"]
