version: '3.8'
networks:
   cynergideploynet:
      name: cynergideploynet
services:
   cynergipgdb:
      container_name: cynergipgdb
      image: cynergipgdbbase
      build:
         context: ../development/cynergipgdb
         dockerfile: cynergipgdb.dockerfile
   cynergitestdeploydb:
      container_name: cynergitestdeploydb
      networks:
         - cynergideploynet
      build:
         context: ../development/cynergitestdb
         dockerfile: cynergitestdb.dockerfile
      tmpfs: /var/lib/postgresql/data:rw
      volumes:
         - ../development/cynergitestdb/fastinfo:/tmp/fastinfo
      environment:
         - POSTGRES_DB=cynergitestdb
         - POSTGRES_PASSWORD=password
   cynergidbready:
      container_name: cynergidbready
      image: cynergipgdbbase
      networks:
         - cynergideploynet
      depends_on:
         - cynergitestdeploydb
      links:
        - cynergitestdeploydb
      stdin_open: true
      tty: true
      command: [ "/root/db-ready.sh", "cynergitestdeploydb" ]
   cynmid:
      container_name: cynmid
      build:
         context: ./cynmid
         dockerfile: cynmid.dockerfile
      volumes:
         - ../../:/home/jenkins/cynergi-middleware
         - ./gradleCache:/home/jenkins/caches
         - ./gradleWrapper:/home/jenkins/wrapper
      stdin_open: true
      tty: true
      networks:
         - cynergideploynet
      links:
         - cynergitestdeploydb
      command: ["/home/jenkins/cynergi-middleware/support/deployment/cynmid/build-cynmid.sh"]
